n = "JNPGCZBUXHJAVWXGWIZAXTIQYMRRSSYDNUWCJYVZVZZCYZYKWUMOJNZYUJIKCWXUVDDNOYJDXYIXADXJYZNZTSNQDXGUBYSZPRCRPQYIPTXCSIHNZXWFWSQKVYOHWIZJYWZDQSLPIFXRYWYLXWWYDCBWIKJQGWSUXPHCORZXSXLWWOIZPIMQXCWVCMAYWKKPRNWAYYATXCHQCZKTIWIRLOZVQWKXZGYRZUQJXDJQQYMYLNBZXWWMJXPZXKYPGWRETBPPDHUMQMKNUYHFGQKHMYKJKWYTIBZSTOZFHLQVYXLGCNIEXQFAGBWAFMXSWXTCWZKXSAXUZFLUYPWIGKWYUDTOOYYWZYQZXDVJSYSTGJWXNZGZOZSZCXCHZERWCIWYTIPQRWXZWCYYQYUWTNGZXZUBYKYVZWPEKOYZNWKYGPOYXLTWYYTAFYXPXXQWCWSZLMXRGKVCCWLANWWCBZYWLIRYGJRHMKWVBWXWGRLETQNZHYAQUTZK"

# sの文字列をeach_charで1文字ずつ取り出しcount_hashに文字の出現回数を格納している 
# ex)hello → {"h" => 1, "e" => 1, "l" => 2, "o" => 1}
#　Xの3つ先がXでなければEに変換する
# 273から5つ表示する
result = n.gsub("W","")
result = result.gsub("YZ","E")
# result = []
count = 0
result.each_char do |t|
    count += 1
    if count == 27 ||count == 271 ||count == 272 ||count == 273 || count == 274 || count == 275 || count == 276 || count == 277
        puts t

    end
end

